application: nyangame-1315
version: 1
runtime: python27
api_version: 1
threadsafe: yes

#[START handlers]
handlers:
- url: /(.+)
  static_files: public/\1
  upload: public/(.*)

- url: /
  static_files: public/home.html
  upload: public/index.html
# [END handlers]

# [START libraries]
libraries:
- name: markupsafe
  version: "0.15"
- name: jinja2
  version: "2.6"
# [END libraries]

