application: nyangame
version: 1
runtime: python27
api_version: 1
threadsafe: yes

#[START handlers]
handlers:
- url: /(.+)
  static_files: public/\1
  upload: public/(.*)

- url: /
  static_files: public/index.html
  upload: public/index.html
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]

